name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: 'v1.0.0-dev'
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run composer install
        run: composer install --no-dev --no-interaction --no-progress --optimize-autoloader

      - name: Copy files to tmp folder
        run: mkdir -p ./tmp && cp -r ./src ./composer.json ./composer.lock ./README.md ./tmp

      - name: Create ZIP file
        run: zip -r ./release.zip ./tmp

      - name: Create Release
        # if: startsWith(github.ref, 'refs/tags/v')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.inputs.version || github.ref }}
          release_name: ${{ github.event.inputs.version || github.ref }}
          body: |
          draft: false
          prerelease: false

      - name: Upload release.zip to Release
        # if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: release.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
